/**
 * Witness Adapter
 * Handles BFT timestamping for ballot creation, votes, and results
 *
 * Witness provides cryptographic proof that something existed at a specific time.
 * Multiple witnesses sign the timestamp, requiring a threshold for validity.
 *
 * API v1:
 * - POST /v1/timestamp { hash: "hex" } -> { attestation: SignedAttestation }
 * - POST /v1/verify { attestation: SignedAttestation } -> { valid, verified_signatures, required_signatures }
 * - GET /v1/config -> NetworkConfig with witness info and threshold
 */

import type {
  WitnessAttestation,
  Hash,
  SophiaWitnessSignedAttestation,
} from '../types.js';

export interface WitnessConfig {
  gatewayUrl: string;
  timeout?: number;
  /** Minimum signatures required (fetched from server if not set) */
  threshold?: number;
}

/**
 * Witness API response types
 */
interface TimestampResponse {
  attestation: SignedAttestationResponse;
  status?: 'confirmed' | 'pending' | 'rejected';
}

interface SignedAttestationResponse {
  attestation: {
    hash: string;
    timestamp: number;
    network_id: string;
    sequence: number;
  };
  signatures: MultiSigSignatures | AggregatedSignatures;
}

interface MultiSigSignatures {
  signatures: Array<{
    witness_id: string;
    signature: string;
  }>;
}

interface AggregatedSignatures {
  signature: string;
  signers: string[];    // list of witness IDs
}

interface VerifyResponse {
  valid: boolean;
  verified_signatures: number;
  required_signatures: number;
  message: string;
}

interface NetworkConfigResponse {
  id: string;
  witnesses: Array<{
    id: string;
    pubkey: string;
    endpoint: string;
  }>;
  threshold: number;
  signature_scheme: 'ed25519' | 'bls';
}

const CONTRACT_VERSION = 'sophia/v1' as const;

function lowerHex(value: string, name: string): string {
  const normalized = value.toLowerCase();
  if (!/^[0-9a-f]+$/.test(normalized)) {
    throw new WitnessError(`${name} must be lowercase hex`, 'INVALID_ATTESTATION');
  }
  return normalized;
}

function sha256Hex(value: string, name: string): string {
  const normalized = lowerHex(value, name);
  if (normalized.length !== 64) {
    throw new WitnessError(`${name} must be a 32-byte SHA-256 hex value`, 'INVALID_ATTESTATION');
  }
  return normalized;
}

function normalizeSignatureSet(signatures: MultiSigSignatures | AggregatedSignatures | SophiaWitnessSignedAttestation['signatures']): SophiaWitnessSignedAttestation['signatures'] {
  if ('kind' in signatures) {
    if (signatures.kind === 'multisig') {
      return {
        kind: 'multisig',
        signatures: signatures.signatures.map((signature, index) => ({
          witness_id: signature.witness_id,
          signature: lowerHex(signature.signature, `signatures[${index}].signature`),
        })),
      };
    }
    return {
      kind: 'aggregated',
      signature: lowerHex(signatures.signature, 'signatures.signature'),
      signers: [...signatures.signers],
    };
  }

  if ('signatures' in signatures) {
    return {
      kind: 'multisig',
      signatures: signatures.signatures.map((signature, index) => ({
        witness_id: signature.witness_id,
        signature: lowerHex(signature.signature, `signatures[${index}].signature`),
      })),
    };
  }

  return {
    kind: 'aggregated',
    signature: lowerHex(signatures.signature, 'signatures.signature'),
    signers: [...signatures.signers],
  };
}

function normalizeSignedAttestation(raw: SignedAttestationResponse | SophiaWitnessSignedAttestation): SophiaWitnessSignedAttestation {
  const attestation = raw.attestation;
  return {
    contract_version: CONTRACT_VERSION,
    artifact_type: 'witness.signed_attestation',
    attestation: {
      hash: sha256Hex(attestation.hash, 'attestation.hash'),
      timestamp: attestation.timestamp,
      network_id: attestation.network_id,
      sequence: attestation.sequence,
    },
    signatures: normalizeSignatureSet(raw.signatures),
  };
}

function toWireSignedAttestation(canonical: SophiaWitnessSignedAttestation): SignedAttestationResponse {
  const signatures = canonical.signatures.kind === 'multisig'
    ? {
        signatures: canonical.signatures.signatures.map(signature => ({
          witness_id: signature.witness_id,
          signature: signature.signature,
        })),
      }
    : {
        signature: canonical.signatures.signature,
        signers: [...canonical.signatures.signers],
      };

  return {
    attestation: { ...canonical.attestation },
    signatures,
  };
}

export interface WitnessAdapter {
  /**
   * Get an attestation for a hash
   * Note: timestamp is generated by the witness service
   */
  attest(hash: Hash): Promise<WitnessAttestation>;

  /**
   * Verify an attestation is valid
   */
  verify(attestation: WitnessAttestation): Promise<boolean>;

  /**
   * Check if the Witness service is available
   */
  healthCheck(): Promise<boolean>;
}

/**
 * HTTP-based Witness adapter for production use
 */
export class HttpWitnessAdapter implements WitnessAdapter {
  private timeout: number;
  private threshold: number | null;
  private networkConfig: NetworkConfigResponse | null = null;

  constructor(private config: WitnessConfig) {
    this.timeout = config.timeout ?? 10000;
    this.threshold = config.threshold ?? null;
  }

  /**
   * Fetch network configuration (including threshold)
   */
  private async fetchConfig(): Promise<void> {
    if (this.networkConfig) return;

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.timeout);

    try {
      const response = await fetch(`${this.config.gatewayUrl}/v1/config`, {
        signal: controller.signal,
      });

      if (response.ok) {
        this.networkConfig = await response.json() as NetworkConfigResponse;
        if (this.threshold === null) {
          this.threshold = this.networkConfig.threshold;
        }
        console.log(`[Witness] Connected to network: ${this.networkConfig.id} (threshold: ${this.networkConfig.threshold})`);
      }
    } catch {
      // Config fetch is optional, use defaults
    } finally {
      clearTimeout(timeoutId);
    }
  }

  async attest(hash: Hash): Promise<WitnessAttestation> {
    await this.fetchConfig();

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.timeout);
    const url = `${this.config.gatewayUrl}/v1/timestamp`;

    try {
      console.log(`[Witness] POST ${url}`);
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ hash }),  // Just hash, server generates timestamp
        signal: controller.signal,
      });

      if (!response.ok) {
        const body = await response.text().catch(() => '');
        throw new WitnessError(
          `Failed to get attestation: ${response.status} ${response.statusText} - ${url}${body ? ` - ${body}` : ''}`,
          'ATTEST_FAILED'
        );
      }

      const data = await response.json() as TimestampResponse;
      return this.parseAttestation(data);
    } finally {
      clearTimeout(timeoutId);
    }
  }

  /**
   * Parse the nested attestation response into WitnessAttestation
   */
  private parseAttestation(data: TimestampResponse): WitnessAttestation {
    const canonical = normalizeSignedAttestation(data.attestation);
    const { attestation, signatures } = canonical;

    if (signatures.kind === 'multisig') {
      const witnessSignatures = signatures.signatures.map(s => ({
        witnessId: s.witness_id,
        signature: s.signature,
      }));
      return {
        hash: attestation.hash,
        timestamp: attestation.timestamp,
        signatures: witnessSignatures,
        witnessIds: witnessSignatures.map(s => s.witnessId),
        networkId: attestation.network_id,
        sequence: attestation.sequence,
        signatureType: 'multisig',
        canonical,
      };
    }

    return {
      hash: attestation.hash,
      timestamp: attestation.timestamp,
      signatures: [],  // Individual sigs not available in BLS aggregated mode
      witnessIds: signatures.signers,
      networkId: attestation.network_id,
      sequence: attestation.sequence,
      signatureType: 'aggregated',
      aggregatedSignature: signatures.signature,
      canonical,
    };
  }

  async verify(attestation: WitnessAttestation): Promise<boolean> {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.timeout);

    try {
      const apiAttestation = toWireSignedAttestation(this.toCanonicalSignedAttestation(attestation));

      const response = await fetch(`${this.config.gatewayUrl}/v1/verify`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ attestation: apiAttestation }),
        signal: controller.signal,
      });

      if (!response.ok) {
        return false;
      }

      const data = await response.json() as VerifyResponse;
      return data.valid === true;
    } catch {
      console.warn('[Witness] Verification failed');
      return false;
    } finally {
      clearTimeout(timeoutId);
    }
  }

  private toCanonicalSignedAttestation(attestation: WitnessAttestation): SophiaWitnessSignedAttestation {
    if (attestation.canonical) {
      return normalizeSignedAttestation(attestation.canonical);
    }

    if (attestation.signatureType === 'aggregated' && attestation.aggregatedSignature) {
      return {
        contract_version: CONTRACT_VERSION,
        artifact_type: 'witness.signed_attestation',
        attestation: {
          hash: sha256Hex(attestation.hash, 'attestation.hash'),
          timestamp: attestation.timestamp,
          network_id: attestation.networkId ?? 'prestige',
          sequence: attestation.sequence ?? 0,
        },
        signatures: {
          kind: 'aggregated',
          signature: attestation.aggregatedSignature,
          signers: attestation.witnessIds,
        },
      };
    }

    return {
      contract_version: CONTRACT_VERSION,
      artifact_type: 'witness.signed_attestation',
      attestation: {
        hash: sha256Hex(attestation.hash, 'attestation.hash'),
        timestamp: attestation.timestamp,
        network_id: attestation.networkId ?? 'prestige',
        sequence: attestation.sequence ?? 0,
      },
      signatures: {
        kind: 'multisig',
        signatures: attestation.signatures.map(s => ({
          witness_id: s.witnessId,
          signature: s.signature,
        })),
      },
    };
  }

  async healthCheck(): Promise<boolean> {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 5000);

    try {
      const response = await fetch(`${this.config.gatewayUrl}/health`, {
        signal: controller.signal,
      });
      return response.ok;
    } catch {
      return false;
    } finally {
      clearTimeout(timeoutId);
    }
  }
}

/**
 * Mock Witness adapter for testing and development
 */
export class MockWitnessAdapter implements WitnessAdapter {
  private attestations = new Map<string, WitnessAttestation>();
  private witnessIds = ['witness-1', 'witness-2', 'witness-3'];
  private threshold: number;
  private networkId = 'mock-network';
  private sequence = 0;

  constructor(options?: { threshold?: number; networkId?: string }) {
    this.threshold = options?.threshold ?? 2;
    if (options?.networkId) {
      this.networkId = options.networkId;
    }
  }

  async attest(hash: Hash): Promise<WitnessAttestation> {
    // Server generates timestamp
    const timestamp = Math.floor(Date.now() / 1000);
    this.sequence++;

    const attestation: WitnessAttestation = {
      hash,
      timestamp,
      signatures: this.witnessIds.slice(0, this.threshold).map(id => ({
        witnessId: id,
        signature: `mock-sig-${id}-${hash.slice(0, 8)}-${timestamp}`,
      })),
      witnessIds: this.witnessIds.slice(0, this.threshold),
      networkId: this.networkId,
      sequence: this.sequence,
    };

    this.attestations.set(hash, attestation);
    return attestation;
  }

  async verify(attestation: WitnessAttestation): Promise<boolean> {
    // Check threshold
    if (attestation.signatures.length < this.threshold) {
      return false;
    }

    // Check all witness IDs are valid
    const validWitnesses = attestation.witnessIds.every(id =>
      this.witnessIds.includes(id)
    );
    if (!validWitnesses) {
      return false;
    }

    // Check signatures match witness IDs
    const signatureWitnessIds = attestation.signatures.map(s => s.witnessId);
    const signaturesValid = attestation.witnessIds.every(id =>
      signatureWitnessIds.includes(id)
    );

    return signaturesValid;
  }

  async healthCheck(): Promise<boolean> {
    return true;
  }

  // Test helpers
  setWitnessIds(ids: string[]): void {
    this.witnessIds = ids;
  }

  setThreshold(threshold: number): void {
    this.threshold = threshold;
  }

  clearAttestations(): void {
    this.attestations.clear();
  }
}

/**
 * Witness-specific error
 */
class WitnessError extends Error {
  constructor(message: string, public code: string) {
    super(message);
    this.name = 'WitnessError';
  }
}
